package Exception;

public class ExceptionPropagation {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			method1();
		}
		catch(Exception e) {
			System.out.println("Exception caught " + e.getMessage());
		}

	}
	public static void method1() throws Exception{
		System.out.println("inside method1");
		method2();
	}
	
	public static void method2() throws Exception{
		System.out.println("inside method2");
		throw new Exception("Exception occured in method2");
	}

}
